// This file is generated by automatic
// script, don't modify it, modify the generator instead.
// Generator can be found under src/gen-scelet/
#include "naming_utils.h"
#include <sys/syscall.h>
#include <sys/ptrace.h>
#include <signal.h>

/* returns string description of syscall, or NULL */
const char* get_syscall_name(long id) {
    static int initialized = 0;
    static const char* names[1000] = {0};
    if (!initialized) {
        initialized = 1;
#ifdef SYS_accept4
        if (0 <= SYS_accept4 && SYS_accept4 < 1000)
            names[SYS_accept4] = "accept4";
#endif
#ifdef SYS_accept
        if (0 <= SYS_accept && SYS_accept < 1000)
            names[SYS_accept] = "accept";
#endif
#ifdef SYS_access
        if (0 <= SYS_access && SYS_access < 1000)
            names[SYS_access] = "access";
#endif
#ifdef SYS_acct
        if (0 <= SYS_acct && SYS_acct < 1000)
            names[SYS_acct] = "acct";
#endif
#ifdef SYS_add_key
        if (0 <= SYS_add_key && SYS_add_key < 1000)
            names[SYS_add_key] = "add_key";
#endif
#ifdef SYS_adjtimex
        if (0 <= SYS_adjtimex && SYS_adjtimex < 1000)
            names[SYS_adjtimex] = "adjtimex";
#endif
#ifdef SYS_afs_syscall
        if (0 <= SYS_afs_syscall && SYS_afs_syscall < 1000)
            names[SYS_afs_syscall] = "afs_syscall";
#endif
#ifdef SYS_alarm
        if (0 <= SYS_alarm && SYS_alarm < 1000)
            names[SYS_alarm] = "alarm";
#endif
#ifdef SYS_arch_prctl
        if (0 <= SYS_arch_prctl && SYS_arch_prctl < 1000)
            names[SYS_arch_prctl] = "arch_prctl";
#endif
#ifdef SYS_bdflush
        if (0 <= SYS_bdflush && SYS_bdflush < 1000)
            names[SYS_bdflush] = "bdflush";
#endif
#ifdef SYS_bind
        if (0 <= SYS_bind && SYS_bind < 1000)
            names[SYS_bind] = "bind";
#endif
#ifdef SYS_bpf
        if (0 <= SYS_bpf && SYS_bpf < 1000)
            names[SYS_bpf] = "bpf";
#endif
#ifdef SYS_break
        if (0 <= SYS_break && SYS_break < 1000)
            names[SYS_break] = "break";
#endif
#ifdef SYS_brk
        if (0 <= SYS_brk && SYS_brk < 1000)
            names[SYS_brk] = "brk";
#endif
#ifdef SYS_capget
        if (0 <= SYS_capget && SYS_capget < 1000)
            names[SYS_capget] = "capget";
#endif
#ifdef SYS_capset
        if (0 <= SYS_capset && SYS_capset < 1000)
            names[SYS_capset] = "capset";
#endif
#ifdef SYS_chdir
        if (0 <= SYS_chdir && SYS_chdir < 1000)
            names[SYS_chdir] = "chdir";
#endif
#ifdef SYS_chmod
        if (0 <= SYS_chmod && SYS_chmod < 1000)
            names[SYS_chmod] = "chmod";
#endif
#ifdef SYS_chown32
        if (0 <= SYS_chown32 && SYS_chown32 < 1000)
            names[SYS_chown32] = "chown32";
#endif
#ifdef SYS_chown
        if (0 <= SYS_chown && SYS_chown < 1000)
            names[SYS_chown] = "chown";
#endif
#ifdef SYS_chroot
        if (0 <= SYS_chroot && SYS_chroot < 1000)
            names[SYS_chroot] = "chroot";
#endif
#ifdef SYS_clock_adjtime
        if (0 <= SYS_clock_adjtime && SYS_clock_adjtime < 1000)
            names[SYS_clock_adjtime] = "clock_adjtime";
#endif
#ifdef SYS_clock_getres
        if (0 <= SYS_clock_getres && SYS_clock_getres < 1000)
            names[SYS_clock_getres] = "clock_getres";
#endif
#ifdef SYS_clock_gettime
        if (0 <= SYS_clock_gettime && SYS_clock_gettime < 1000)
            names[SYS_clock_gettime] = "clock_gettime";
#endif
#ifdef SYS_clock_nanosleep
        if (0 <= SYS_clock_nanosleep && SYS_clock_nanosleep < 1000)
            names[SYS_clock_nanosleep] = "clock_nanosleep";
#endif
#ifdef SYS_clock_settime
        if (0 <= SYS_clock_settime && SYS_clock_settime < 1000)
            names[SYS_clock_settime] = "clock_settime";
#endif
#ifdef SYS_clone
        if (0 <= SYS_clone && SYS_clone < 1000)
            names[SYS_clone] = "clone";
#endif
#ifdef SYS_close
        if (0 <= SYS_close && SYS_close < 1000)
            names[SYS_close] = "close";
#endif
#ifdef SYS_connect
        if (0 <= SYS_connect && SYS_connect < 1000)
            names[SYS_connect] = "connect";
#endif
#ifdef SYS_create_module
        if (0 <= SYS_create_module && SYS_create_module < 1000)
            names[SYS_create_module] = "create_module";
#endif
#ifdef SYS_creat
        if (0 <= SYS_creat && SYS_creat < 1000)
            names[SYS_creat] = "creat";
#endif
#ifdef SYS_delete_module
        if (0 <= SYS_delete_module && SYS_delete_module < 1000)
            names[SYS_delete_module] = "delete_module";
#endif
#ifdef SYS_dup2
        if (0 <= SYS_dup2 && SYS_dup2 < 1000)
            names[SYS_dup2] = "dup2";
#endif
#ifdef SYS_dup3
        if (0 <= SYS_dup3 && SYS_dup3 < 1000)
            names[SYS_dup3] = "dup3";
#endif
#ifdef SYS_dup
        if (0 <= SYS_dup && SYS_dup < 1000)
            names[SYS_dup] = "dup";
#endif
#ifdef SYS_epoll_create1
        if (0 <= SYS_epoll_create1 && SYS_epoll_create1 < 1000)
            names[SYS_epoll_create1] = "epoll_create1";
#endif
#ifdef SYS_epoll_create
        if (0 <= SYS_epoll_create && SYS_epoll_create < 1000)
            names[SYS_epoll_create] = "epoll_create";
#endif
#ifdef SYS_epoll_ctl
        if (0 <= SYS_epoll_ctl && SYS_epoll_ctl < 1000)
            names[SYS_epoll_ctl] = "epoll_ctl";
#endif
#ifdef SYS_epoll_ctl_old
        if (0 <= SYS_epoll_ctl_old && SYS_epoll_ctl_old < 1000)
            names[SYS_epoll_ctl_old] = "epoll_ctl_old";
#endif
#ifdef SYS_epoll_pwait
        if (0 <= SYS_epoll_pwait && SYS_epoll_pwait < 1000)
            names[SYS_epoll_pwait] = "epoll_pwait";
#endif
#ifdef SYS_epoll_wait
        if (0 <= SYS_epoll_wait && SYS_epoll_wait < 1000)
            names[SYS_epoll_wait] = "epoll_wait";
#endif
#ifdef SYS_epoll_wait_old
        if (0 <= SYS_epoll_wait_old && SYS_epoll_wait_old < 1000)
            names[SYS_epoll_wait_old] = "epoll_wait_old";
#endif
#ifdef SYS_eventfd2
        if (0 <= SYS_eventfd2 && SYS_eventfd2 < 1000)
            names[SYS_eventfd2] = "eventfd2";
#endif
#ifdef SYS_eventfd
        if (0 <= SYS_eventfd && SYS_eventfd < 1000)
            names[SYS_eventfd] = "eventfd";
#endif
#ifdef SYS_execve
        if (0 <= SYS_execve && SYS_execve < 1000)
            names[SYS_execve] = "execve";
#endif
#ifdef SYS_exit_group
        if (0 <= SYS_exit_group && SYS_exit_group < 1000)
            names[SYS_exit_group] = "exit_group";
#endif
#ifdef SYS_exit
        if (0 <= SYS_exit && SYS_exit < 1000)
            names[SYS_exit] = "exit";
#endif
#ifdef SYS_faccessat
        if (0 <= SYS_faccessat && SYS_faccessat < 1000)
            names[SYS_faccessat] = "faccessat";
#endif
#ifdef SYS_fadvise64_64
        if (0 <= SYS_fadvise64_64 && SYS_fadvise64_64 < 1000)
            names[SYS_fadvise64_64] = "fadvise64_64";
#endif
#ifdef SYS_fadvise64
        if (0 <= SYS_fadvise64 && SYS_fadvise64 < 1000)
            names[SYS_fadvise64] = "fadvise64";
#endif
#ifdef SYS_fallocate
        if (0 <= SYS_fallocate && SYS_fallocate < 1000)
            names[SYS_fallocate] = "fallocate";
#endif
#ifdef SYS_fanotify_init
        if (0 <= SYS_fanotify_init && SYS_fanotify_init < 1000)
            names[SYS_fanotify_init] = "fanotify_init";
#endif
#ifdef SYS_fanotify_mark
        if (0 <= SYS_fanotify_mark && SYS_fanotify_mark < 1000)
            names[SYS_fanotify_mark] = "fanotify_mark";
#endif
#ifdef SYS_fchdir
        if (0 <= SYS_fchdir && SYS_fchdir < 1000)
            names[SYS_fchdir] = "fchdir";
#endif
#ifdef SYS_fchmodat
        if (0 <= SYS_fchmodat && SYS_fchmodat < 1000)
            names[SYS_fchmodat] = "fchmodat";
#endif
#ifdef SYS_fchmod
        if (0 <= SYS_fchmod && SYS_fchmod < 1000)
            names[SYS_fchmod] = "fchmod";
#endif
#ifdef SYS_fchown32
        if (0 <= SYS_fchown32 && SYS_fchown32 < 1000)
            names[SYS_fchown32] = "fchown32";
#endif
#ifdef SYS_fchownat
        if (0 <= SYS_fchownat && SYS_fchownat < 1000)
            names[SYS_fchownat] = "fchownat";
#endif
#ifdef SYS_fchown
        if (0 <= SYS_fchown && SYS_fchown < 1000)
            names[SYS_fchown] = "fchown";
#endif
#ifdef SYS_fcntl64
        if (0 <= SYS_fcntl64 && SYS_fcntl64 < 1000)
            names[SYS_fcntl64] = "fcntl64";
#endif
#ifdef SYS_fcntl
        if (0 <= SYS_fcntl && SYS_fcntl < 1000)
            names[SYS_fcntl] = "fcntl";
#endif
#ifdef SYS_fdatasync
        if (0 <= SYS_fdatasync && SYS_fdatasync < 1000)
            names[SYS_fdatasync] = "fdatasync";
#endif
#ifdef SYS_fgetxattr
        if (0 <= SYS_fgetxattr && SYS_fgetxattr < 1000)
            names[SYS_fgetxattr] = "fgetxattr";
#endif
#ifdef SYS_finit_module
        if (0 <= SYS_finit_module && SYS_finit_module < 1000)
            names[SYS_finit_module] = "finit_module";
#endif
#ifdef SYS_flistxattr
        if (0 <= SYS_flistxattr && SYS_flistxattr < 1000)
            names[SYS_flistxattr] = "flistxattr";
#endif
#ifdef SYS_flock
        if (0 <= SYS_flock && SYS_flock < 1000)
            names[SYS_flock] = "flock";
#endif
#ifdef SYS_fork
        if (0 <= SYS_fork && SYS_fork < 1000)
            names[SYS_fork] = "fork";
#endif
#ifdef SYS_fremovexattr
        if (0 <= SYS_fremovexattr && SYS_fremovexattr < 1000)
            names[SYS_fremovexattr] = "fremovexattr";
#endif
#ifdef SYS_fsetxattr
        if (0 <= SYS_fsetxattr && SYS_fsetxattr < 1000)
            names[SYS_fsetxattr] = "fsetxattr";
#endif
#ifdef SYS_fstat64
        if (0 <= SYS_fstat64 && SYS_fstat64 < 1000)
            names[SYS_fstat64] = "fstat64";
#endif
#ifdef SYS_fstatat64
        if (0 <= SYS_fstatat64 && SYS_fstatat64 < 1000)
            names[SYS_fstatat64] = "fstatat64";
#endif
#ifdef SYS_fstatfs64
        if (0 <= SYS_fstatfs64 && SYS_fstatfs64 < 1000)
            names[SYS_fstatfs64] = "fstatfs64";
#endif
#ifdef SYS_fstatfs
        if (0 <= SYS_fstatfs && SYS_fstatfs < 1000)
            names[SYS_fstatfs] = "fstatfs";
#endif
#ifdef SYS_fstat
        if (0 <= SYS_fstat && SYS_fstat < 1000)
            names[SYS_fstat] = "fstat";
#endif
#ifdef SYS_fsync
        if (0 <= SYS_fsync && SYS_fsync < 1000)
            names[SYS_fsync] = "fsync";
#endif
#ifdef SYS_ftime
        if (0 <= SYS_ftime && SYS_ftime < 1000)
            names[SYS_ftime] = "ftime";
#endif
#ifdef SYS_ftruncate64
        if (0 <= SYS_ftruncate64 && SYS_ftruncate64 < 1000)
            names[SYS_ftruncate64] = "ftruncate64";
#endif
#ifdef SYS_ftruncate
        if (0 <= SYS_ftruncate && SYS_ftruncate < 1000)
            names[SYS_ftruncate] = "ftruncate";
#endif
#ifdef SYS_futex
        if (0 <= SYS_futex && SYS_futex < 1000)
            names[SYS_futex] = "futex";
#endif
#ifdef SYS_futimesat
        if (0 <= SYS_futimesat && SYS_futimesat < 1000)
            names[SYS_futimesat] = "futimesat";
#endif
#ifdef SYS_getcpu
        if (0 <= SYS_getcpu && SYS_getcpu < 1000)
            names[SYS_getcpu] = "getcpu";
#endif
#ifdef SYS_getcwd
        if (0 <= SYS_getcwd && SYS_getcwd < 1000)
            names[SYS_getcwd] = "getcwd";
#endif
#ifdef SYS_getdents64
        if (0 <= SYS_getdents64 && SYS_getdents64 < 1000)
            names[SYS_getdents64] = "getdents64";
#endif
#ifdef SYS_getdents
        if (0 <= SYS_getdents && SYS_getdents < 1000)
            names[SYS_getdents] = "getdents";
#endif
#ifdef SYS_getegid32
        if (0 <= SYS_getegid32 && SYS_getegid32 < 1000)
            names[SYS_getegid32] = "getegid32";
#endif
#ifdef SYS_getegid
        if (0 <= SYS_getegid && SYS_getegid < 1000)
            names[SYS_getegid] = "getegid";
#endif
#ifdef SYS_geteuid32
        if (0 <= SYS_geteuid32 && SYS_geteuid32 < 1000)
            names[SYS_geteuid32] = "geteuid32";
#endif
#ifdef SYS_geteuid
        if (0 <= SYS_geteuid && SYS_geteuid < 1000)
            names[SYS_geteuid] = "geteuid";
#endif
#ifdef SYS_getgid32
        if (0 <= SYS_getgid32 && SYS_getgid32 < 1000)
            names[SYS_getgid32] = "getgid32";
#endif
#ifdef SYS_getgid
        if (0 <= SYS_getgid && SYS_getgid < 1000)
            names[SYS_getgid] = "getgid";
#endif
#ifdef SYS_getgroups32
        if (0 <= SYS_getgroups32 && SYS_getgroups32 < 1000)
            names[SYS_getgroups32] = "getgroups32";
#endif
#ifdef SYS_getgroups
        if (0 <= SYS_getgroups && SYS_getgroups < 1000)
            names[SYS_getgroups] = "getgroups";
#endif
#ifdef SYS_getitimer
        if (0 <= SYS_getitimer && SYS_getitimer < 1000)
            names[SYS_getitimer] = "getitimer";
#endif
#ifdef SYS_get_kernel_syms
        if (0 <= SYS_get_kernel_syms && SYS_get_kernel_syms < 1000)
            names[SYS_get_kernel_syms] = "get_kernel_syms";
#endif
#ifdef SYS_get_mempolicy
        if (0 <= SYS_get_mempolicy && SYS_get_mempolicy < 1000)
            names[SYS_get_mempolicy] = "get_mempolicy";
#endif
#ifdef SYS_getpeername
        if (0 <= SYS_getpeername && SYS_getpeername < 1000)
            names[SYS_getpeername] = "getpeername";
#endif
#ifdef SYS_getpgid
        if (0 <= SYS_getpgid && SYS_getpgid < 1000)
            names[SYS_getpgid] = "getpgid";
#endif
#ifdef SYS_getpgrp
        if (0 <= SYS_getpgrp && SYS_getpgrp < 1000)
            names[SYS_getpgrp] = "getpgrp";
#endif
#ifdef SYS_getpid
        if (0 <= SYS_getpid && SYS_getpid < 1000)
            names[SYS_getpid] = "getpid";
#endif
#ifdef SYS_getpmsg
        if (0 <= SYS_getpmsg && SYS_getpmsg < 1000)
            names[SYS_getpmsg] = "getpmsg";
#endif
#ifdef SYS_getppid
        if (0 <= SYS_getppid && SYS_getppid < 1000)
            names[SYS_getppid] = "getppid";
#endif
#ifdef SYS_getpriority
        if (0 <= SYS_getpriority && SYS_getpriority < 1000)
            names[SYS_getpriority] = "getpriority";
#endif
#ifdef SYS_getrandom
        if (0 <= SYS_getrandom && SYS_getrandom < 1000)
            names[SYS_getrandom] = "getrandom";
#endif
#ifdef SYS_getresgid32
        if (0 <= SYS_getresgid32 && SYS_getresgid32 < 1000)
            names[SYS_getresgid32] = "getresgid32";
#endif
#ifdef SYS_getresgid
        if (0 <= SYS_getresgid && SYS_getresgid < 1000)
            names[SYS_getresgid] = "getresgid";
#endif
#ifdef SYS_getresuid32
        if (0 <= SYS_getresuid32 && SYS_getresuid32 < 1000)
            names[SYS_getresuid32] = "getresuid32";
#endif
#ifdef SYS_getresuid
        if (0 <= SYS_getresuid && SYS_getresuid < 1000)
            names[SYS_getresuid] = "getresuid";
#endif
#ifdef SYS_getrlimit
        if (0 <= SYS_getrlimit && SYS_getrlimit < 1000)
            names[SYS_getrlimit] = "getrlimit";
#endif
#ifdef SYS_get_robust_list
        if (0 <= SYS_get_robust_list && SYS_get_robust_list < 1000)
            names[SYS_get_robust_list] = "get_robust_list";
#endif
#ifdef SYS_getrusage
        if (0 <= SYS_getrusage && SYS_getrusage < 1000)
            names[SYS_getrusage] = "getrusage";
#endif
#ifdef SYS_getsid
        if (0 <= SYS_getsid && SYS_getsid < 1000)
            names[SYS_getsid] = "getsid";
#endif
#ifdef SYS_getsockname
        if (0 <= SYS_getsockname && SYS_getsockname < 1000)
            names[SYS_getsockname] = "getsockname";
#endif
#ifdef SYS_getsockopt
        if (0 <= SYS_getsockopt && SYS_getsockopt < 1000)
            names[SYS_getsockopt] = "getsockopt";
#endif
#ifdef SYS_get_thread_area
        if (0 <= SYS_get_thread_area && SYS_get_thread_area < 1000)
            names[SYS_get_thread_area] = "get_thread_area";
#endif
#ifdef SYS_gettid
        if (0 <= SYS_gettid && SYS_gettid < 1000)
            names[SYS_gettid] = "gettid";
#endif
#ifdef SYS_gettimeofday
        if (0 <= SYS_gettimeofday && SYS_gettimeofday < 1000)
            names[SYS_gettimeofday] = "gettimeofday";
#endif
#ifdef SYS_getuid32
        if (0 <= SYS_getuid32 && SYS_getuid32 < 1000)
            names[SYS_getuid32] = "getuid32";
#endif
#ifdef SYS_getuid
        if (0 <= SYS_getuid && SYS_getuid < 1000)
            names[SYS_getuid] = "getuid";
#endif
#ifdef SYS_getxattr
        if (0 <= SYS_getxattr && SYS_getxattr < 1000)
            names[SYS_getxattr] = "getxattr";
#endif
#ifdef SYS_gtty
        if (0 <= SYS_gtty && SYS_gtty < 1000)
            names[SYS_gtty] = "gtty";
#endif
#ifdef SYS_idle
        if (0 <= SYS_idle && SYS_idle < 1000)
            names[SYS_idle] = "idle";
#endif
#ifdef SYS_init_module
        if (0 <= SYS_init_module && SYS_init_module < 1000)
            names[SYS_init_module] = "init_module";
#endif
#ifdef SYS_inotify_add_watch
        if (0 <= SYS_inotify_add_watch && SYS_inotify_add_watch < 1000)
            names[SYS_inotify_add_watch] = "inotify_add_watch";
#endif
#ifdef SYS_inotify_init1
        if (0 <= SYS_inotify_init1 && SYS_inotify_init1 < 1000)
            names[SYS_inotify_init1] = "inotify_init1";
#endif
#ifdef SYS_inotify_init
        if (0 <= SYS_inotify_init && SYS_inotify_init < 1000)
            names[SYS_inotify_init] = "inotify_init";
#endif
#ifdef SYS_inotify_rm_watch
        if (0 <= SYS_inotify_rm_watch && SYS_inotify_rm_watch < 1000)
            names[SYS_inotify_rm_watch] = "inotify_rm_watch";
#endif
#ifdef SYS_io_cancel
        if (0 <= SYS_io_cancel && SYS_io_cancel < 1000)
            names[SYS_io_cancel] = "io_cancel";
#endif
#ifdef SYS_ioctl
        if (0 <= SYS_ioctl && SYS_ioctl < 1000)
            names[SYS_ioctl] = "ioctl";
#endif
#ifdef SYS_io_destroy
        if (0 <= SYS_io_destroy && SYS_io_destroy < 1000)
            names[SYS_io_destroy] = "io_destroy";
#endif
#ifdef SYS_io_getevents
        if (0 <= SYS_io_getevents && SYS_io_getevents < 1000)
            names[SYS_io_getevents] = "io_getevents";
#endif
#ifdef SYS_ioperm
        if (0 <= SYS_ioperm && SYS_ioperm < 1000)
            names[SYS_ioperm] = "ioperm";
#endif
#ifdef SYS_iopl
        if (0 <= SYS_iopl && SYS_iopl < 1000)
            names[SYS_iopl] = "iopl";
#endif
#ifdef SYS_ioprio_get
        if (0 <= SYS_ioprio_get && SYS_ioprio_get < 1000)
            names[SYS_ioprio_get] = "ioprio_get";
#endif
#ifdef SYS_ioprio_set
        if (0 <= SYS_ioprio_set && SYS_ioprio_set < 1000)
            names[SYS_ioprio_set] = "ioprio_set";
#endif
#ifdef SYS_io_setup
        if (0 <= SYS_io_setup && SYS_io_setup < 1000)
            names[SYS_io_setup] = "io_setup";
#endif
#ifdef SYS_io_submit
        if (0 <= SYS_io_submit && SYS_io_submit < 1000)
            names[SYS_io_submit] = "io_submit";
#endif
#ifdef SYS_ipc
        if (0 <= SYS_ipc && SYS_ipc < 1000)
            names[SYS_ipc] = "ipc";
#endif
#ifdef SYS_kcmp
        if (0 <= SYS_kcmp && SYS_kcmp < 1000)
            names[SYS_kcmp] = "kcmp";
#endif
#ifdef SYS_kexec_file_load
        if (0 <= SYS_kexec_file_load && SYS_kexec_file_load < 1000)
            names[SYS_kexec_file_load] = "kexec_file_load";
#endif
#ifdef SYS_kexec_load
        if (0 <= SYS_kexec_load && SYS_kexec_load < 1000)
            names[SYS_kexec_load] = "kexec_load";
#endif
#ifdef SYS_keyctl
        if (0 <= SYS_keyctl && SYS_keyctl < 1000)
            names[SYS_keyctl] = "keyctl";
#endif
#ifdef SYS_kill
        if (0 <= SYS_kill && SYS_kill < 1000)
            names[SYS_kill] = "kill";
#endif
#ifdef SYS_lchown32
        if (0 <= SYS_lchown32 && SYS_lchown32 < 1000)
            names[SYS_lchown32] = "lchown32";
#endif
#ifdef SYS_lchown
        if (0 <= SYS_lchown && SYS_lchown < 1000)
            names[SYS_lchown] = "lchown";
#endif
#ifdef SYS_lgetxattr
        if (0 <= SYS_lgetxattr && SYS_lgetxattr < 1000)
            names[SYS_lgetxattr] = "lgetxattr";
#endif
#ifdef SYS_linkat
        if (0 <= SYS_linkat && SYS_linkat < 1000)
            names[SYS_linkat] = "linkat";
#endif
#ifdef SYS_link
        if (0 <= SYS_link && SYS_link < 1000)
            names[SYS_link] = "link";
#endif
#ifdef SYS_listen
        if (0 <= SYS_listen && SYS_listen < 1000)
            names[SYS_listen] = "listen";
#endif
#ifdef SYS_listxattr
        if (0 <= SYS_listxattr && SYS_listxattr < 1000)
            names[SYS_listxattr] = "listxattr";
#endif
#ifdef SYS_llistxattr
        if (0 <= SYS_llistxattr && SYS_llistxattr < 1000)
            names[SYS_llistxattr] = "llistxattr";
#endif
#ifdef SYS__llseek
        if (0 <= SYS__llseek && SYS__llseek < 1000)
            names[SYS__llseek] = "_llseek";
#endif
#ifdef SYS_lock
        if (0 <= SYS_lock && SYS_lock < 1000)
            names[SYS_lock] = "lock";
#endif
#ifdef SYS_lookup_dcookie
        if (0 <= SYS_lookup_dcookie && SYS_lookup_dcookie < 1000)
            names[SYS_lookup_dcookie] = "lookup_dcookie";
#endif
#ifdef SYS_lremovexattr
        if (0 <= SYS_lremovexattr && SYS_lremovexattr < 1000)
            names[SYS_lremovexattr] = "lremovexattr";
#endif
#ifdef SYS_lseek
        if (0 <= SYS_lseek && SYS_lseek < 1000)
            names[SYS_lseek] = "lseek";
#endif
#ifdef SYS_lsetxattr
        if (0 <= SYS_lsetxattr && SYS_lsetxattr < 1000)
            names[SYS_lsetxattr] = "lsetxattr";
#endif
#ifdef SYS_lstat64
        if (0 <= SYS_lstat64 && SYS_lstat64 < 1000)
            names[SYS_lstat64] = "lstat64";
#endif
#ifdef SYS_lstat
        if (0 <= SYS_lstat && SYS_lstat < 1000)
            names[SYS_lstat] = "lstat";
#endif
#ifdef SYS_madvise
        if (0 <= SYS_madvise && SYS_madvise < 1000)
            names[SYS_madvise] = "madvise";
#endif
#ifdef SYS_mbind
        if (0 <= SYS_mbind && SYS_mbind < 1000)
            names[SYS_mbind] = "mbind";
#endif
#ifdef SYS_memfd_create
        if (0 <= SYS_memfd_create && SYS_memfd_create < 1000)
            names[SYS_memfd_create] = "memfd_create";
#endif
#ifdef SYS_migrate_pages
        if (0 <= SYS_migrate_pages && SYS_migrate_pages < 1000)
            names[SYS_migrate_pages] = "migrate_pages";
#endif
#ifdef SYS_mincore
        if (0 <= SYS_mincore && SYS_mincore < 1000)
            names[SYS_mincore] = "mincore";
#endif
#ifdef SYS_mkdirat
        if (0 <= SYS_mkdirat && SYS_mkdirat < 1000)
            names[SYS_mkdirat] = "mkdirat";
#endif
#ifdef SYS_mkdir
        if (0 <= SYS_mkdir && SYS_mkdir < 1000)
            names[SYS_mkdir] = "mkdir";
#endif
#ifdef SYS_mknodat
        if (0 <= SYS_mknodat && SYS_mknodat < 1000)
            names[SYS_mknodat] = "mknodat";
#endif
#ifdef SYS_mknod
        if (0 <= SYS_mknod && SYS_mknod < 1000)
            names[SYS_mknod] = "mknod";
#endif
#ifdef SYS_mlockall
        if (0 <= SYS_mlockall && SYS_mlockall < 1000)
            names[SYS_mlockall] = "mlockall";
#endif
#ifdef SYS_mlock
        if (0 <= SYS_mlock && SYS_mlock < 1000)
            names[SYS_mlock] = "mlock";
#endif
#ifdef SYS_mmap2
        if (0 <= SYS_mmap2 && SYS_mmap2 < 1000)
            names[SYS_mmap2] = "mmap2";
#endif
#ifdef SYS_mmap
        if (0 <= SYS_mmap && SYS_mmap < 1000)
            names[SYS_mmap] = "mmap";
#endif
#ifdef SYS_modify_ldt
        if (0 <= SYS_modify_ldt && SYS_modify_ldt < 1000)
            names[SYS_modify_ldt] = "modify_ldt";
#endif
#ifdef SYS_mount
        if (0 <= SYS_mount && SYS_mount < 1000)
            names[SYS_mount] = "mount";
#endif
#ifdef SYS_move_pages
        if (0 <= SYS_move_pages && SYS_move_pages < 1000)
            names[SYS_move_pages] = "move_pages";
#endif
#ifdef SYS_mprotect
        if (0 <= SYS_mprotect && SYS_mprotect < 1000)
            names[SYS_mprotect] = "mprotect";
#endif
#ifdef SYS_mpx
        if (0 <= SYS_mpx && SYS_mpx < 1000)
            names[SYS_mpx] = "mpx";
#endif
#ifdef SYS_mq_getsetattr
        if (0 <= SYS_mq_getsetattr && SYS_mq_getsetattr < 1000)
            names[SYS_mq_getsetattr] = "mq_getsetattr";
#endif
#ifdef SYS_mq_notify
        if (0 <= SYS_mq_notify && SYS_mq_notify < 1000)
            names[SYS_mq_notify] = "mq_notify";
#endif
#ifdef SYS_mq_open
        if (0 <= SYS_mq_open && SYS_mq_open < 1000)
            names[SYS_mq_open] = "mq_open";
#endif
#ifdef SYS_mq_timedreceive
        if (0 <= SYS_mq_timedreceive && SYS_mq_timedreceive < 1000)
            names[SYS_mq_timedreceive] = "mq_timedreceive";
#endif
#ifdef SYS_mq_timedsend
        if (0 <= SYS_mq_timedsend && SYS_mq_timedsend < 1000)
            names[SYS_mq_timedsend] = "mq_timedsend";
#endif
#ifdef SYS_mq_unlink
        if (0 <= SYS_mq_unlink && SYS_mq_unlink < 1000)
            names[SYS_mq_unlink] = "mq_unlink";
#endif
#ifdef SYS_mremap
        if (0 <= SYS_mremap && SYS_mremap < 1000)
            names[SYS_mremap] = "mremap";
#endif
#ifdef SYS_msgctl
        if (0 <= SYS_msgctl && SYS_msgctl < 1000)
            names[SYS_msgctl] = "msgctl";
#endif
#ifdef SYS_msgget
        if (0 <= SYS_msgget && SYS_msgget < 1000)
            names[SYS_msgget] = "msgget";
#endif
#ifdef SYS_msgrcv
        if (0 <= SYS_msgrcv && SYS_msgrcv < 1000)
            names[SYS_msgrcv] = "msgrcv";
#endif
#ifdef SYS_msgsnd
        if (0 <= SYS_msgsnd && SYS_msgsnd < 1000)
            names[SYS_msgsnd] = "msgsnd";
#endif
#ifdef SYS_msync
        if (0 <= SYS_msync && SYS_msync < 1000)
            names[SYS_msync] = "msync";
#endif
#ifdef SYS_munlockall
        if (0 <= SYS_munlockall && SYS_munlockall < 1000)
            names[SYS_munlockall] = "munlockall";
#endif
#ifdef SYS_munlock
        if (0 <= SYS_munlock && SYS_munlock < 1000)
            names[SYS_munlock] = "munlock";
#endif
#ifdef SYS_munmap
        if (0 <= SYS_munmap && SYS_munmap < 1000)
            names[SYS_munmap] = "munmap";
#endif
#ifdef SYS_name_to_handle_at
        if (0 <= SYS_name_to_handle_at && SYS_name_to_handle_at < 1000)
            names[SYS_name_to_handle_at] = "name_to_handle_at";
#endif
#ifdef SYS_nanosleep
        if (0 <= SYS_nanosleep && SYS_nanosleep < 1000)
            names[SYS_nanosleep] = "nanosleep";
#endif
#ifdef SYS_newfstatat
        if (0 <= SYS_newfstatat && SYS_newfstatat < 1000)
            names[SYS_newfstatat] = "newfstatat";
#endif
#ifdef SYS__newselect
        if (0 <= SYS__newselect && SYS__newselect < 1000)
            names[SYS__newselect] = "_newselect";
#endif
#ifdef SYS_nfsservctl
        if (0 <= SYS_nfsservctl && SYS_nfsservctl < 1000)
            names[SYS_nfsservctl] = "nfsservctl";
#endif
#ifdef SYS_nice
        if (0 <= SYS_nice && SYS_nice < 1000)
            names[SYS_nice] = "nice";
#endif
#ifdef SYS_oldfstat
        if (0 <= SYS_oldfstat && SYS_oldfstat < 1000)
            names[SYS_oldfstat] = "oldfstat";
#endif
#ifdef SYS_oldlstat
        if (0 <= SYS_oldlstat && SYS_oldlstat < 1000)
            names[SYS_oldlstat] = "oldlstat";
#endif
#ifdef SYS_oldolduname
        if (0 <= SYS_oldolduname && SYS_oldolduname < 1000)
            names[SYS_oldolduname] = "oldolduname";
#endif
#ifdef SYS_oldstat
        if (0 <= SYS_oldstat && SYS_oldstat < 1000)
            names[SYS_oldstat] = "oldstat";
#endif
#ifdef SYS_olduname
        if (0 <= SYS_olduname && SYS_olduname < 1000)
            names[SYS_olduname] = "olduname";
#endif
#ifdef SYS_openat
        if (0 <= SYS_openat && SYS_openat < 1000)
            names[SYS_openat] = "openat";
#endif
#ifdef SYS_open_by_handle_at
        if (0 <= SYS_open_by_handle_at && SYS_open_by_handle_at < 1000)
            names[SYS_open_by_handle_at] = "open_by_handle_at";
#endif
#ifdef SYS_open
        if (0 <= SYS_open && SYS_open < 1000)
            names[SYS_open] = "open";
#endif
#ifdef SYS_pause
        if (0 <= SYS_pause && SYS_pause < 1000)
            names[SYS_pause] = "pause";
#endif
#ifdef SYS_perf_event_open
        if (0 <= SYS_perf_event_open && SYS_perf_event_open < 1000)
            names[SYS_perf_event_open] = "perf_event_open";
#endif
#ifdef SYS_personality
        if (0 <= SYS_personality && SYS_personality < 1000)
            names[SYS_personality] = "personality";
#endif
#ifdef SYS_pipe2
        if (0 <= SYS_pipe2 && SYS_pipe2 < 1000)
            names[SYS_pipe2] = "pipe2";
#endif
#ifdef SYS_pipe
        if (0 <= SYS_pipe && SYS_pipe < 1000)
            names[SYS_pipe] = "pipe";
#endif
#ifdef SYS_pivot_root
        if (0 <= SYS_pivot_root && SYS_pivot_root < 1000)
            names[SYS_pivot_root] = "pivot_root";
#endif
#ifdef SYS_poll
        if (0 <= SYS_poll && SYS_poll < 1000)
            names[SYS_poll] = "poll";
#endif
#ifdef SYS_ppoll
        if (0 <= SYS_ppoll && SYS_ppoll < 1000)
            names[SYS_ppoll] = "ppoll";
#endif
#ifdef SYS_prctl
        if (0 <= SYS_prctl && SYS_prctl < 1000)
            names[SYS_prctl] = "prctl";
#endif
#ifdef SYS_pread64
        if (0 <= SYS_pread64 && SYS_pread64 < 1000)
            names[SYS_pread64] = "pread64";
#endif
#ifdef SYS_preadv
        if (0 <= SYS_preadv && SYS_preadv < 1000)
            names[SYS_preadv] = "preadv";
#endif
#ifdef SYS_prlimit64
        if (0 <= SYS_prlimit64 && SYS_prlimit64 < 1000)
            names[SYS_prlimit64] = "prlimit64";
#endif
#ifdef SYS_process_vm_readv
        if (0 <= SYS_process_vm_readv && SYS_process_vm_readv < 1000)
            names[SYS_process_vm_readv] = "process_vm_readv";
#endif
#ifdef SYS_process_vm_writev
        if (0 <= SYS_process_vm_writev && SYS_process_vm_writev < 1000)
            names[SYS_process_vm_writev] = "process_vm_writev";
#endif
#ifdef SYS_profil
        if (0 <= SYS_profil && SYS_profil < 1000)
            names[SYS_profil] = "profil";
#endif
#ifdef SYS_prof
        if (0 <= SYS_prof && SYS_prof < 1000)
            names[SYS_prof] = "prof";
#endif
#ifdef SYS_pselect6
        if (0 <= SYS_pselect6 && SYS_pselect6 < 1000)
            names[SYS_pselect6] = "pselect6";
#endif
#ifdef SYS_ptrace
        if (0 <= SYS_ptrace && SYS_ptrace < 1000)
            names[SYS_ptrace] = "ptrace";
#endif
#ifdef SYS_putpmsg
        if (0 <= SYS_putpmsg && SYS_putpmsg < 1000)
            names[SYS_putpmsg] = "putpmsg";
#endif
#ifdef SYS_pwrite64
        if (0 <= SYS_pwrite64 && SYS_pwrite64 < 1000)
            names[SYS_pwrite64] = "pwrite64";
#endif
#ifdef SYS_pwritev
        if (0 <= SYS_pwritev && SYS_pwritev < 1000)
            names[SYS_pwritev] = "pwritev";
#endif
#ifdef SYS_query_module
        if (0 <= SYS_query_module && SYS_query_module < 1000)
            names[SYS_query_module] = "query_module";
#endif
#ifdef SYS_quotactl
        if (0 <= SYS_quotactl && SYS_quotactl < 1000)
            names[SYS_quotactl] = "quotactl";
#endif
#ifdef SYS_readahead
        if (0 <= SYS_readahead && SYS_readahead < 1000)
            names[SYS_readahead] = "readahead";
#endif
#ifdef SYS_readdir
        if (0 <= SYS_readdir && SYS_readdir < 1000)
            names[SYS_readdir] = "readdir";
#endif
#ifdef SYS_readlinkat
        if (0 <= SYS_readlinkat && SYS_readlinkat < 1000)
            names[SYS_readlinkat] = "readlinkat";
#endif
#ifdef SYS_readlink
        if (0 <= SYS_readlink && SYS_readlink < 1000)
            names[SYS_readlink] = "readlink";
#endif
#ifdef SYS_read
        if (0 <= SYS_read && SYS_read < 1000)
            names[SYS_read] = "read";
#endif
#ifdef SYS_readv
        if (0 <= SYS_readv && SYS_readv < 1000)
            names[SYS_readv] = "readv";
#endif
#ifdef SYS_reboot
        if (0 <= SYS_reboot && SYS_reboot < 1000)
            names[SYS_reboot] = "reboot";
#endif
#ifdef SYS_recvfrom
        if (0 <= SYS_recvfrom && SYS_recvfrom < 1000)
            names[SYS_recvfrom] = "recvfrom";
#endif
#ifdef SYS_recvmmsg
        if (0 <= SYS_recvmmsg && SYS_recvmmsg < 1000)
            names[SYS_recvmmsg] = "recvmmsg";
#endif
#ifdef SYS_recvmsg
        if (0 <= SYS_recvmsg && SYS_recvmsg < 1000)
            names[SYS_recvmsg] = "recvmsg";
#endif
#ifdef SYS_remap_file_pages
        if (0 <= SYS_remap_file_pages && SYS_remap_file_pages < 1000)
            names[SYS_remap_file_pages] = "remap_file_pages";
#endif
#ifdef SYS_removexattr
        if (0 <= SYS_removexattr && SYS_removexattr < 1000)
            names[SYS_removexattr] = "removexattr";
#endif
#ifdef SYS_renameat2
        if (0 <= SYS_renameat2 && SYS_renameat2 < 1000)
            names[SYS_renameat2] = "renameat2";
#endif
#ifdef SYS_renameat
        if (0 <= SYS_renameat && SYS_renameat < 1000)
            names[SYS_renameat] = "renameat";
#endif
#ifdef SYS_rename
        if (0 <= SYS_rename && SYS_rename < 1000)
            names[SYS_rename] = "rename";
#endif
#ifdef SYS_request_key
        if (0 <= SYS_request_key && SYS_request_key < 1000)
            names[SYS_request_key] = "request_key";
#endif
#ifdef SYS_restart_syscall
        if (0 <= SYS_restart_syscall && SYS_restart_syscall < 1000)
            names[SYS_restart_syscall] = "restart_syscall";
#endif
#ifdef SYS_rmdir
        if (0 <= SYS_rmdir && SYS_rmdir < 1000)
            names[SYS_rmdir] = "rmdir";
#endif
#ifdef SYS_rt_sigaction
        if (0 <= SYS_rt_sigaction && SYS_rt_sigaction < 1000)
            names[SYS_rt_sigaction] = "rt_sigaction";
#endif
#ifdef SYS_rt_sigpending
        if (0 <= SYS_rt_sigpending && SYS_rt_sigpending < 1000)
            names[SYS_rt_sigpending] = "rt_sigpending";
#endif
#ifdef SYS_rt_sigprocmask
        if (0 <= SYS_rt_sigprocmask && SYS_rt_sigprocmask < 1000)
            names[SYS_rt_sigprocmask] = "rt_sigprocmask";
#endif
#ifdef SYS_rt_sigqueueinfo
        if (0 <= SYS_rt_sigqueueinfo && SYS_rt_sigqueueinfo < 1000)
            names[SYS_rt_sigqueueinfo] = "rt_sigqueueinfo";
#endif
#ifdef SYS_rt_sigreturn
        if (0 <= SYS_rt_sigreturn && SYS_rt_sigreturn < 1000)
            names[SYS_rt_sigreturn] = "rt_sigreturn";
#endif
#ifdef SYS_rt_sigsuspend
        if (0 <= SYS_rt_sigsuspend && SYS_rt_sigsuspend < 1000)
            names[SYS_rt_sigsuspend] = "rt_sigsuspend";
#endif
#ifdef SYS_rt_sigtimedwait
        if (0 <= SYS_rt_sigtimedwait && SYS_rt_sigtimedwait < 1000)
            names[SYS_rt_sigtimedwait] = "rt_sigtimedwait";
#endif
#ifdef SYS_rt_tgsigqueueinfo
        if (0 <= SYS_rt_tgsigqueueinfo && SYS_rt_tgsigqueueinfo < 1000)
            names[SYS_rt_tgsigqueueinfo] = "rt_tgsigqueueinfo";
#endif
#ifdef SYS_sched_getaffinity
        if (0 <= SYS_sched_getaffinity && SYS_sched_getaffinity < 1000)
            names[SYS_sched_getaffinity] = "sched_getaffinity";
#endif
#ifdef SYS_sched_getattr
        if (0 <= SYS_sched_getattr && SYS_sched_getattr < 1000)
            names[SYS_sched_getattr] = "sched_getattr";
#endif
#ifdef SYS_sched_getparam
        if (0 <= SYS_sched_getparam && SYS_sched_getparam < 1000)
            names[SYS_sched_getparam] = "sched_getparam";
#endif
#ifdef SYS_sched_get_priority_max
        if (0 <= SYS_sched_get_priority_max && SYS_sched_get_priority_max < 1000)
            names[SYS_sched_get_priority_max] = "sched_get_priority_max";
#endif
#ifdef SYS_sched_get_priority_min
        if (0 <= SYS_sched_get_priority_min && SYS_sched_get_priority_min < 1000)
            names[SYS_sched_get_priority_min] = "sched_get_priority_min";
#endif
#ifdef SYS_sched_getscheduler
        if (0 <= SYS_sched_getscheduler && SYS_sched_getscheduler < 1000)
            names[SYS_sched_getscheduler] = "sched_getscheduler";
#endif
#ifdef SYS_sched_rr_get_interval
        if (0 <= SYS_sched_rr_get_interval && SYS_sched_rr_get_interval < 1000)
            names[SYS_sched_rr_get_interval] = "sched_rr_get_interval";
#endif
#ifdef SYS_sched_setaffinity
        if (0 <= SYS_sched_setaffinity && SYS_sched_setaffinity < 1000)
            names[SYS_sched_setaffinity] = "sched_setaffinity";
#endif
#ifdef SYS_sched_setattr
        if (0 <= SYS_sched_setattr && SYS_sched_setattr < 1000)
            names[SYS_sched_setattr] = "sched_setattr";
#endif
#ifdef SYS_sched_setparam
        if (0 <= SYS_sched_setparam && SYS_sched_setparam < 1000)
            names[SYS_sched_setparam] = "sched_setparam";
#endif
#ifdef SYS_sched_setscheduler
        if (0 <= SYS_sched_setscheduler && SYS_sched_setscheduler < 1000)
            names[SYS_sched_setscheduler] = "sched_setscheduler";
#endif
#ifdef SYS_sched_yield
        if (0 <= SYS_sched_yield && SYS_sched_yield < 1000)
            names[SYS_sched_yield] = "sched_yield";
#endif
#ifdef SYS_seccomp
        if (0 <= SYS_seccomp && SYS_seccomp < 1000)
            names[SYS_seccomp] = "seccomp";
#endif
#ifdef SYS_security
        if (0 <= SYS_security && SYS_security < 1000)
            names[SYS_security] = "security";
#endif
#ifdef SYS_select
        if (0 <= SYS_select && SYS_select < 1000)
            names[SYS_select] = "select";
#endif
#ifdef SYS_semctl
        if (0 <= SYS_semctl && SYS_semctl < 1000)
            names[SYS_semctl] = "semctl";
#endif
#ifdef SYS_semget
        if (0 <= SYS_semget && SYS_semget < 1000)
            names[SYS_semget] = "semget";
#endif
#ifdef SYS_semop
        if (0 <= SYS_semop && SYS_semop < 1000)
            names[SYS_semop] = "semop";
#endif
#ifdef SYS_semtimedop
        if (0 <= SYS_semtimedop && SYS_semtimedop < 1000)
            names[SYS_semtimedop] = "semtimedop";
#endif
#ifdef SYS_sendfile64
        if (0 <= SYS_sendfile64 && SYS_sendfile64 < 1000)
            names[SYS_sendfile64] = "sendfile64";
#endif
#ifdef SYS_sendfile
        if (0 <= SYS_sendfile && SYS_sendfile < 1000)
            names[SYS_sendfile] = "sendfile";
#endif
#ifdef SYS_sendmmsg
        if (0 <= SYS_sendmmsg && SYS_sendmmsg < 1000)
            names[SYS_sendmmsg] = "sendmmsg";
#endif
#ifdef SYS_sendmsg
        if (0 <= SYS_sendmsg && SYS_sendmsg < 1000)
            names[SYS_sendmsg] = "sendmsg";
#endif
#ifdef SYS_sendto
        if (0 <= SYS_sendto && SYS_sendto < 1000)
            names[SYS_sendto] = "sendto";
#endif
#ifdef SYS_setdomainname
        if (0 <= SYS_setdomainname && SYS_setdomainname < 1000)
            names[SYS_setdomainname] = "setdomainname";
#endif
#ifdef SYS_setfsgid32
        if (0 <= SYS_setfsgid32 && SYS_setfsgid32 < 1000)
            names[SYS_setfsgid32] = "setfsgid32";
#endif
#ifdef SYS_setfsgid
        if (0 <= SYS_setfsgid && SYS_setfsgid < 1000)
            names[SYS_setfsgid] = "setfsgid";
#endif
#ifdef SYS_setfsuid32
        if (0 <= SYS_setfsuid32 && SYS_setfsuid32 < 1000)
            names[SYS_setfsuid32] = "setfsuid32";
#endif
#ifdef SYS_setfsuid
        if (0 <= SYS_setfsuid && SYS_setfsuid < 1000)
            names[SYS_setfsuid] = "setfsuid";
#endif
#ifdef SYS_setgid32
        if (0 <= SYS_setgid32 && SYS_setgid32 < 1000)
            names[SYS_setgid32] = "setgid32";
#endif
#ifdef SYS_setgid
        if (0 <= SYS_setgid && SYS_setgid < 1000)
            names[SYS_setgid] = "setgid";
#endif
#ifdef SYS_setgroups32
        if (0 <= SYS_setgroups32 && SYS_setgroups32 < 1000)
            names[SYS_setgroups32] = "setgroups32";
#endif
#ifdef SYS_setgroups
        if (0 <= SYS_setgroups && SYS_setgroups < 1000)
            names[SYS_setgroups] = "setgroups";
#endif
#ifdef SYS_sethostname
        if (0 <= SYS_sethostname && SYS_sethostname < 1000)
            names[SYS_sethostname] = "sethostname";
#endif
#ifdef SYS_setitimer
        if (0 <= SYS_setitimer && SYS_setitimer < 1000)
            names[SYS_setitimer] = "setitimer";
#endif
#ifdef SYS_set_mempolicy
        if (0 <= SYS_set_mempolicy && SYS_set_mempolicy < 1000)
            names[SYS_set_mempolicy] = "set_mempolicy";
#endif
#ifdef SYS_setns
        if (0 <= SYS_setns && SYS_setns < 1000)
            names[SYS_setns] = "setns";
#endif
#ifdef SYS_setpgid
        if (0 <= SYS_setpgid && SYS_setpgid < 1000)
            names[SYS_setpgid] = "setpgid";
#endif
#ifdef SYS_setpriority
        if (0 <= SYS_setpriority && SYS_setpriority < 1000)
            names[SYS_setpriority] = "setpriority";
#endif
#ifdef SYS_setregid32
        if (0 <= SYS_setregid32 && SYS_setregid32 < 1000)
            names[SYS_setregid32] = "setregid32";
#endif
#ifdef SYS_setregid
        if (0 <= SYS_setregid && SYS_setregid < 1000)
            names[SYS_setregid] = "setregid";
#endif
#ifdef SYS_setresgid32
        if (0 <= SYS_setresgid32 && SYS_setresgid32 < 1000)
            names[SYS_setresgid32] = "setresgid32";
#endif
#ifdef SYS_setresgid
        if (0 <= SYS_setresgid && SYS_setresgid < 1000)
            names[SYS_setresgid] = "setresgid";
#endif
#ifdef SYS_setresuid32
        if (0 <= SYS_setresuid32 && SYS_setresuid32 < 1000)
            names[SYS_setresuid32] = "setresuid32";
#endif
#ifdef SYS_setresuid
        if (0 <= SYS_setresuid && SYS_setresuid < 1000)
            names[SYS_setresuid] = "setresuid";
#endif
#ifdef SYS_setreuid32
        if (0 <= SYS_setreuid32 && SYS_setreuid32 < 1000)
            names[SYS_setreuid32] = "setreuid32";
#endif
#ifdef SYS_setreuid
        if (0 <= SYS_setreuid && SYS_setreuid < 1000)
            names[SYS_setreuid] = "setreuid";
#endif
#ifdef SYS_setrlimit
        if (0 <= SYS_setrlimit && SYS_setrlimit < 1000)
            names[SYS_setrlimit] = "setrlimit";
#endif
#ifdef SYS_set_robust_list
        if (0 <= SYS_set_robust_list && SYS_set_robust_list < 1000)
            names[SYS_set_robust_list] = "set_robust_list";
#endif
#ifdef SYS_setsid
        if (0 <= SYS_setsid && SYS_setsid < 1000)
            names[SYS_setsid] = "setsid";
#endif
#ifdef SYS_setsockopt
        if (0 <= SYS_setsockopt && SYS_setsockopt < 1000)
            names[SYS_setsockopt] = "setsockopt";
#endif
#ifdef SYS_set_thread_area
        if (0 <= SYS_set_thread_area && SYS_set_thread_area < 1000)
            names[SYS_set_thread_area] = "set_thread_area";
#endif
#ifdef SYS_set_tid_address
        if (0 <= SYS_set_tid_address && SYS_set_tid_address < 1000)
            names[SYS_set_tid_address] = "set_tid_address";
#endif
#ifdef SYS_settimeofday
        if (0 <= SYS_settimeofday && SYS_settimeofday < 1000)
            names[SYS_settimeofday] = "settimeofday";
#endif
#ifdef SYS_setuid32
        if (0 <= SYS_setuid32 && SYS_setuid32 < 1000)
            names[SYS_setuid32] = "setuid32";
#endif
#ifdef SYS_setuid
        if (0 <= SYS_setuid && SYS_setuid < 1000)
            names[SYS_setuid] = "setuid";
#endif
#ifdef SYS_setxattr
        if (0 <= SYS_setxattr && SYS_setxattr < 1000)
            names[SYS_setxattr] = "setxattr";
#endif
#ifdef SYS_sgetmask
        if (0 <= SYS_sgetmask && SYS_sgetmask < 1000)
            names[SYS_sgetmask] = "sgetmask";
#endif
#ifdef SYS_shmat
        if (0 <= SYS_shmat && SYS_shmat < 1000)
            names[SYS_shmat] = "shmat";
#endif
#ifdef SYS_shmctl
        if (0 <= SYS_shmctl && SYS_shmctl < 1000)
            names[SYS_shmctl] = "shmctl";
#endif
#ifdef SYS_shmdt
        if (0 <= SYS_shmdt && SYS_shmdt < 1000)
            names[SYS_shmdt] = "shmdt";
#endif
#ifdef SYS_shmget
        if (0 <= SYS_shmget && SYS_shmget < 1000)
            names[SYS_shmget] = "shmget";
#endif
#ifdef SYS_shutdown
        if (0 <= SYS_shutdown && SYS_shutdown < 1000)
            names[SYS_shutdown] = "shutdown";
#endif
#ifdef SYS_sigaction
        if (0 <= SYS_sigaction && SYS_sigaction < 1000)
            names[SYS_sigaction] = "sigaction";
#endif
#ifdef SYS_sigaltstack
        if (0 <= SYS_sigaltstack && SYS_sigaltstack < 1000)
            names[SYS_sigaltstack] = "sigaltstack";
#endif
#ifdef SYS_signalfd4
        if (0 <= SYS_signalfd4 && SYS_signalfd4 < 1000)
            names[SYS_signalfd4] = "signalfd4";
#endif
#ifdef SYS_signalfd
        if (0 <= SYS_signalfd && SYS_signalfd < 1000)
            names[SYS_signalfd] = "signalfd";
#endif
#ifdef SYS_signal
        if (0 <= SYS_signal && SYS_signal < 1000)
            names[SYS_signal] = "signal";
#endif
#ifdef SYS_sigpending
        if (0 <= SYS_sigpending && SYS_sigpending < 1000)
            names[SYS_sigpending] = "sigpending";
#endif
#ifdef SYS_sigprocmask
        if (0 <= SYS_sigprocmask && SYS_sigprocmask < 1000)
            names[SYS_sigprocmask] = "sigprocmask";
#endif
#ifdef SYS_sigreturn
        if (0 <= SYS_sigreturn && SYS_sigreturn < 1000)
            names[SYS_sigreturn] = "sigreturn";
#endif
#ifdef SYS_sigsuspend
        if (0 <= SYS_sigsuspend && SYS_sigsuspend < 1000)
            names[SYS_sigsuspend] = "sigsuspend";
#endif
#ifdef SYS_socketcall
        if (0 <= SYS_socketcall && SYS_socketcall < 1000)
            names[SYS_socketcall] = "socketcall";
#endif
#ifdef SYS_socket
        if (0 <= SYS_socket && SYS_socket < 1000)
            names[SYS_socket] = "socket";
#endif
#ifdef SYS_socketpair
        if (0 <= SYS_socketpair && SYS_socketpair < 1000)
            names[SYS_socketpair] = "socketpair";
#endif
#ifdef SYS_splice
        if (0 <= SYS_splice && SYS_splice < 1000)
            names[SYS_splice] = "splice";
#endif
#ifdef SYS_ssetmask
        if (0 <= SYS_ssetmask && SYS_ssetmask < 1000)
            names[SYS_ssetmask] = "ssetmask";
#endif
#ifdef SYS_stat64
        if (0 <= SYS_stat64 && SYS_stat64 < 1000)
            names[SYS_stat64] = "stat64";
#endif
#ifdef SYS_statfs64
        if (0 <= SYS_statfs64 && SYS_statfs64 < 1000)
            names[SYS_statfs64] = "statfs64";
#endif
#ifdef SYS_statfs
        if (0 <= SYS_statfs && SYS_statfs < 1000)
            names[SYS_statfs] = "statfs";
#endif
#ifdef SYS_stat
        if (0 <= SYS_stat && SYS_stat < 1000)
            names[SYS_stat] = "stat";
#endif
#ifdef SYS_stime
        if (0 <= SYS_stime && SYS_stime < 1000)
            names[SYS_stime] = "stime";
#endif
#ifdef SYS_stty
        if (0 <= SYS_stty && SYS_stty < 1000)
            names[SYS_stty] = "stty";
#endif
#ifdef SYS_swapoff
        if (0 <= SYS_swapoff && SYS_swapoff < 1000)
            names[SYS_swapoff] = "swapoff";
#endif
#ifdef SYS_swapon
        if (0 <= SYS_swapon && SYS_swapon < 1000)
            names[SYS_swapon] = "swapon";
#endif
#ifdef SYS_symlinkat
        if (0 <= SYS_symlinkat && SYS_symlinkat < 1000)
            names[SYS_symlinkat] = "symlinkat";
#endif
#ifdef SYS_symlink
        if (0 <= SYS_symlink && SYS_symlink < 1000)
            names[SYS_symlink] = "symlink";
#endif
#ifdef SYS_sync_file_range
        if (0 <= SYS_sync_file_range && SYS_sync_file_range < 1000)
            names[SYS_sync_file_range] = "sync_file_range";
#endif
#ifdef SYS_syncfs
        if (0 <= SYS_syncfs && SYS_syncfs < 1000)
            names[SYS_syncfs] = "syncfs";
#endif
#ifdef SYS_sync
        if (0 <= SYS_sync && SYS_sync < 1000)
            names[SYS_sync] = "sync";
#endif
#ifdef SYS__sysctl
        if (0 <= SYS__sysctl && SYS__sysctl < 1000)
            names[SYS__sysctl] = "_sysctl";
#endif
#ifdef SYS_sysfs
        if (0 <= SYS_sysfs && SYS_sysfs < 1000)
            names[SYS_sysfs] = "sysfs";
#endif
#ifdef SYS_sysinfo
        if (0 <= SYS_sysinfo && SYS_sysinfo < 1000)
            names[SYS_sysinfo] = "sysinfo";
#endif
#ifdef SYS_syslog
        if (0 <= SYS_syslog && SYS_syslog < 1000)
            names[SYS_syslog] = "syslog";
#endif
#ifdef SYS_tee
        if (0 <= SYS_tee && SYS_tee < 1000)
            names[SYS_tee] = "tee";
#endif
#ifdef SYS_tgkill
        if (0 <= SYS_tgkill && SYS_tgkill < 1000)
            names[SYS_tgkill] = "tgkill";
#endif
#ifdef SYS_time
        if (0 <= SYS_time && SYS_time < 1000)
            names[SYS_time] = "time";
#endif
#ifdef SYS_timer_create
        if (0 <= SYS_timer_create && SYS_timer_create < 1000)
            names[SYS_timer_create] = "timer_create";
#endif
#ifdef SYS_timer_delete
        if (0 <= SYS_timer_delete && SYS_timer_delete < 1000)
            names[SYS_timer_delete] = "timer_delete";
#endif
#ifdef SYS_timerfd_create
        if (0 <= SYS_timerfd_create && SYS_timerfd_create < 1000)
            names[SYS_timerfd_create] = "timerfd_create";
#endif
#ifdef SYS_timerfd_gettime
        if (0 <= SYS_timerfd_gettime && SYS_timerfd_gettime < 1000)
            names[SYS_timerfd_gettime] = "timerfd_gettime";
#endif
#ifdef SYS_timerfd_settime
        if (0 <= SYS_timerfd_settime && SYS_timerfd_settime < 1000)
            names[SYS_timerfd_settime] = "timerfd_settime";
#endif
#ifdef SYS_timer_getoverrun
        if (0 <= SYS_timer_getoverrun && SYS_timer_getoverrun < 1000)
            names[SYS_timer_getoverrun] = "timer_getoverrun";
#endif
#ifdef SYS_timer_gettime
        if (0 <= SYS_timer_gettime && SYS_timer_gettime < 1000)
            names[SYS_timer_gettime] = "timer_gettime";
#endif
#ifdef SYS_timer_settime
        if (0 <= SYS_timer_settime && SYS_timer_settime < 1000)
            names[SYS_timer_settime] = "timer_settime";
#endif
#ifdef SYS_times
        if (0 <= SYS_times && SYS_times < 1000)
            names[SYS_times] = "times";
#endif
#ifdef SYS_tkill
        if (0 <= SYS_tkill && SYS_tkill < 1000)
            names[SYS_tkill] = "tkill";
#endif
#ifdef SYS_truncate64
        if (0 <= SYS_truncate64 && SYS_truncate64 < 1000)
            names[SYS_truncate64] = "truncate64";
#endif
#ifdef SYS_truncate
        if (0 <= SYS_truncate && SYS_truncate < 1000)
            names[SYS_truncate] = "truncate";
#endif
#ifdef SYS_tuxcall
        if (0 <= SYS_tuxcall && SYS_tuxcall < 1000)
            names[SYS_tuxcall] = "tuxcall";
#endif
#ifdef SYS_ugetrlimit
        if (0 <= SYS_ugetrlimit && SYS_ugetrlimit < 1000)
            names[SYS_ugetrlimit] = "ugetrlimit";
#endif
#ifdef SYS_ulimit
        if (0 <= SYS_ulimit && SYS_ulimit < 1000)
            names[SYS_ulimit] = "ulimit";
#endif
#ifdef SYS_umask
        if (0 <= SYS_umask && SYS_umask < 1000)
            names[SYS_umask] = "umask";
#endif
#ifdef SYS_umount2
        if (0 <= SYS_umount2 && SYS_umount2 < 1000)
            names[SYS_umount2] = "umount2";
#endif
#ifdef SYS_umount
        if (0 <= SYS_umount && SYS_umount < 1000)
            names[SYS_umount] = "umount";
#endif
#ifdef SYS_uname
        if (0 <= SYS_uname && SYS_uname < 1000)
            names[SYS_uname] = "uname";
#endif
#ifdef SYS_unlinkat
        if (0 <= SYS_unlinkat && SYS_unlinkat < 1000)
            names[SYS_unlinkat] = "unlinkat";
#endif
#ifdef SYS_unlink
        if (0 <= SYS_unlink && SYS_unlink < 1000)
            names[SYS_unlink] = "unlink";
#endif
#ifdef SYS_unshare
        if (0 <= SYS_unshare && SYS_unshare < 1000)
            names[SYS_unshare] = "unshare";
#endif
#ifdef SYS_uselib
        if (0 <= SYS_uselib && SYS_uselib < 1000)
            names[SYS_uselib] = "uselib";
#endif
#ifdef SYS_ustat
        if (0 <= SYS_ustat && SYS_ustat < 1000)
            names[SYS_ustat] = "ustat";
#endif
#ifdef SYS_utime
        if (0 <= SYS_utime && SYS_utime < 1000)
            names[SYS_utime] = "utime";
#endif
#ifdef SYS_utimensat
        if (0 <= SYS_utimensat && SYS_utimensat < 1000)
            names[SYS_utimensat] = "utimensat";
#endif
#ifdef SYS_utimes
        if (0 <= SYS_utimes && SYS_utimes < 1000)
            names[SYS_utimes] = "utimes";
#endif
#ifdef SYS_vfork
        if (0 <= SYS_vfork && SYS_vfork < 1000)
            names[SYS_vfork] = "vfork";
#endif
#ifdef SYS_vhangup
        if (0 <= SYS_vhangup && SYS_vhangup < 1000)
            names[SYS_vhangup] = "vhangup";
#endif
#ifdef SYS_vm86
        if (0 <= SYS_vm86 && SYS_vm86 < 1000)
            names[SYS_vm86] = "vm86";
#endif
#ifdef SYS_vm86old
        if (0 <= SYS_vm86old && SYS_vm86old < 1000)
            names[SYS_vm86old] = "vm86old";
#endif
#ifdef SYS_vmsplice
        if (0 <= SYS_vmsplice && SYS_vmsplice < 1000)
            names[SYS_vmsplice] = "vmsplice";
#endif
#ifdef SYS_vserver
        if (0 <= SYS_vserver && SYS_vserver < 1000)
            names[SYS_vserver] = "vserver";
#endif
#ifdef SYS_wait4
        if (0 <= SYS_wait4 && SYS_wait4 < 1000)
            names[SYS_wait4] = "wait4";
#endif
#ifdef SYS_waitid
        if (0 <= SYS_waitid && SYS_waitid < 1000)
            names[SYS_waitid] = "waitid";
#endif
#ifdef SYS_waitpid
        if (0 <= SYS_waitpid && SYS_waitpid < 1000)
            names[SYS_waitpid] = "waitpid";
#endif
#ifdef SYS_write
        if (0 <= SYS_write && SYS_write < 1000)
            names[SYS_write] = "write";
#endif
#ifdef SYS_writev
        if (0 <= SYS_writev && SYS_writev < 1000)
            names[SYS_writev] = "writev";
#endif
    }
    if (0 <= id && id < 1000)
        return names[id];
    return 0;
}
/* returns string description of signal, or NULL */
const char* get_signal_name(long id) {
    static int initialized = 0;
    static const char* names[100] = {0};
    if (!initialized) {
        initialized = 1;
#ifdef SIGHUP
        if (0 <= SIGHUP && SIGHUP < 100)
            names[SIGHUP] = "SIGHUP";
#endif
#ifdef SIGINT
        if (0 <= SIGINT && SIGINT < 100)
            names[SIGINT] = "SIGINT";
#endif
#ifdef SIGQUIT
        if (0 <= SIGQUIT && SIGQUIT < 100)
            names[SIGQUIT] = "SIGQUIT";
#endif
#ifdef SIGILL
        if (0 <= SIGILL && SIGILL < 100)
            names[SIGILL] = "SIGILL";
#endif
#ifdef SIGTRAP
        if (0 <= SIGTRAP && SIGTRAP < 100)
            names[SIGTRAP] = "SIGTRAP";
#endif
#ifdef SIGABRT
        if (0 <= SIGABRT && SIGABRT < 100)
            names[SIGABRT] = "SIGABRT";
#endif
#ifdef SIGBUS
        if (0 <= SIGBUS && SIGBUS < 100)
            names[SIGBUS] = "SIGBUS";
#endif
#ifdef SIGFPE
        if (0 <= SIGFPE && SIGFPE < 100)
            names[SIGFPE] = "SIGFPE";
#endif
#ifdef SIGKILL
        if (0 <= SIGKILL && SIGKILL < 100)
            names[SIGKILL] = "SIGKILL";
#endif
#ifdef SIGUSR1
        if (0 <= SIGUSR1 && SIGUSR1 < 100)
            names[SIGUSR1] = "SIGUSR1";
#endif
#ifdef SIGSEGV
        if (0 <= SIGSEGV && SIGSEGV < 100)
            names[SIGSEGV] = "SIGSEGV";
#endif
#ifdef SIGUSR2
        if (0 <= SIGUSR2 && SIGUSR2 < 100)
            names[SIGUSR2] = "SIGUSR2";
#endif
#ifdef SIGPIPE
        if (0 <= SIGPIPE && SIGPIPE < 100)
            names[SIGPIPE] = "SIGPIPE";
#endif
#ifdef SIGALRM
        if (0 <= SIGALRM && SIGALRM < 100)
            names[SIGALRM] = "SIGALRM";
#endif
#ifdef SIGTERM
        if (0 <= SIGTERM && SIGTERM < 100)
            names[SIGTERM] = "SIGTERM";
#endif
#ifdef SIGSTKFLT
        if (0 <= SIGSTKFLT && SIGSTKFLT < 100)
            names[SIGSTKFLT] = "SIGSTKFLT";
#endif
#ifdef SIGCHLD
        if (0 <= SIGCHLD && SIGCHLD < 100)
            names[SIGCHLD] = "SIGCHLD";
#endif
#ifdef SIGCONT
        if (0 <= SIGCONT && SIGCONT < 100)
            names[SIGCONT] = "SIGCONT";
#endif
#ifdef SIGSTOP
        if (0 <= SIGSTOP && SIGSTOP < 100)
            names[SIGSTOP] = "SIGSTOP";
#endif
#ifdef SIGTSTP
        if (0 <= SIGTSTP && SIGTSTP < 100)
            names[SIGTSTP] = "SIGTSTP";
#endif
#ifdef SIGTTIN
        if (0 <= SIGTTIN && SIGTTIN < 100)
            names[SIGTTIN] = "SIGTTIN";
#endif
#ifdef SIGTTOU
        if (0 <= SIGTTOU && SIGTTOU < 100)
            names[SIGTTOU] = "SIGTTOU";
#endif
#ifdef SIGURG
        if (0 <= SIGURG && SIGURG < 100)
            names[SIGURG] = "SIGURG";
#endif
#ifdef SIGXCPU
        if (0 <= SIGXCPU && SIGXCPU < 100)
            names[SIGXCPU] = "SIGXCPU";
#endif
#ifdef SIGXFSZ
        if (0 <= SIGXFSZ && SIGXFSZ < 100)
            names[SIGXFSZ] = "SIGXFSZ";
#endif
#ifdef SIGVTALRM
        if (0 <= SIGVTALRM && SIGVTALRM < 100)
            names[SIGVTALRM] = "SIGVTALRM";
#endif
#ifdef SIGPROF
        if (0 <= SIGPROF && SIGPROF < 100)
            names[SIGPROF] = "SIGPROF";
#endif
#ifdef SIGWINCH
        if (0 <= SIGWINCH && SIGWINCH < 100)
            names[SIGWINCH] = "SIGWINCH";
#endif
#ifdef SIGPWR
        if (0 <= SIGPWR && SIGPWR < 100)
            names[SIGPWR] = "SIGPWR";
#endif
#ifdef SIGSYS
        if (0 <= SIGSYS && SIGSYS < 100)
            names[SIGSYS] = "SIGSYS";
#endif
#ifdef SIGUNUSED
        if (0 <= SIGUNUSED && SIGUNUSED < 100)
            names[SIGUNUSED] = "SIGUNUSED";
#endif
    }
    if (0 <= id && id < 100)
        return names[id];
    return 0;
}
/* returns string description of ptrace event, or NULL */
const char* get_ptraceevent_name(long id) {
    static int initialized = 0;
    static const char* names[20] = {0};
    if (!initialized) {
        initialized = 1;
        if (0 <= PTRACE_EVENT_FORK && PTRACE_EVENT_FORK < 20)
            names[PTRACE_EVENT_FORK] = "PTRACE_EVENT_FORK";
        if (0 <= PTRACE_EVENT_VFORK && PTRACE_EVENT_VFORK < 20)
            names[PTRACE_EVENT_VFORK] = "PTRACE_EVENT_VFORK";
        if (0 <= PTRACE_EVENT_CLONE && PTRACE_EVENT_CLONE < 20)
            names[PTRACE_EVENT_CLONE] = "PTRACE_EVENT_CLONE";
        if (0 <= PTRACE_EVENT_EXEC && PTRACE_EVENT_EXEC < 20)
            names[PTRACE_EVENT_EXEC] = "PTRACE_EVENT_EXEC";
        if (0 <= PTRACE_EVENT_VFORK_DONE && PTRACE_EVENT_VFORK_DONE < 20)
            names[PTRACE_EVENT_VFORK_DONE] = "PTRACE_EVENT_VFORK_DONE";
        if (0 <= PTRACE_EVENT_EXIT && PTRACE_EVENT_EXIT < 20)
            names[PTRACE_EVENT_EXIT] = "PTRACE_EVENT_EXIT";
        if (0 <= PTRACE_EVENT_SECCOMP && PTRACE_EVENT_SECCOMP < 20)
            names[PTRACE_EVENT_SECCOMP] = "PTRACE_EVENT_SECCOMP";
    }
    if (0 <= id && id < 20)
        return names[id];
    return 0;
}
